language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script:
  - npm test:all
  - npm run compile
notifications:
  email:
    on_success: change
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
